# Site settings
title: Lior Kirsch's Blog
email: lior.kirsch [at] gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Machine learning, neuroscience and computational biology.
url: "http://liorkirsch.github.io" # the base hostname & protocol for your site

name: Lior Kirsch
paginate: 10
baseurl: ''
port: 4444
title: Lior Kirsch Webpage
email: lior.kirsch [at] gmail.com
github_username:  liorkirsch

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

gems:
  - jekyll-sitemap






